# Generated by Django 3.1.7 on 2021-04-01 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_item_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='OPEN', max_length=50),
        ),
    ]
