# Generated by Django 3.1.7 on 2021-04-16 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_item_quantity'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['status']},
        ),
        migrations.AddField(
            model_name='order',
            name='orderType',
            field=models.CharField(default='Bopis', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='Open', max_length=50),
        ),
    ]
