# Generated by Django 3.1.7 on 2021-04-28 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20210416_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customerEmail',
            field=models.CharField(default='aking@everestech.com', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='deliveryMethod',
            field=models.CharField(default='Place in trunk', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='licensePlate',
            field=models.CharField(default='ABC12345', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='parkingSpot',
            field=models.CharField(default='3A', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='vehicleDetails',
            field=models.CharField(default='Red Toyota Camry', max_length=50),
        ),
    ]
