# Generated by Django 3.1.7 on 2021-03-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75, unique=True)),
                ('resources', models.ManyToManyField(blank=True, related_name='roles', to='resources.Resource')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
